ratio_names = [
    "marketcap", "enterpriseValue",
    "earningsdate", "exdivdate",
    "sharesOutClass", "sharesout", "sharesgrowthyoy", "sharesgrowthqoq", "sharesInsiders", "sharesInstitutions", "float",
    "pe", "peForward", "ps", "psForward", "pb", "ptbvRatio", "pfcf", "pocf", "pegRatio",
    "evEarnings", "evSales", "evEbitda", "evEbit", "evFcf",
    "currentRatio", "quickRatio", "debtEquity", "debtEbitda", "debtFcf", "interestCoverage",
    "roe", "roa", "roic", "roce", "revPerEmployee", "profitPerEmployee", "employees", "assetturnover", "inventoryturnover",
    "taxexp", "taxrate",
    "beta", "ch1y", "sma50", "sma200", "rsi", "averageVolume",
    "shortInterest", "shortPriorMonth", "shortShares", "shortFloat", "shortRatio",
    "revenue", "gp", "opinc", "pretax", "netinc", "ebitda", "ebit", "eps",
    "totalcash", "debt", "netcash", "netcashpershare", "equity", "bvps", "workingcapital",
    "ncfo", "capex", "fcf", "fcfps",
    "grossMargin", "operatingMargin", "pretaxMargin", "profitMargin", "ebitdaMargin", "ebitMargin", "fcfMargin",
    "dps", "dividendYield", "dividendGrowth", "dividendGrowthYears", "payoutRatio", "buybackYield", "totalReturn", "earningsYield", "fcfYield",
    "priceTarget", "priceTargetChange", "analystRatings", "analystCount", "revenue5y", "eps5y",
    "lastSplitDate", "lastSplitType", "splitRatio",
    "zScore", "fScore"
]

forecast_names = [
    "action_rt",
    "analyst",
    "analysts",
    "average",
    "buy",
    "chart",
    "consensus",
    "count",
    "date",
    "dates",
    "eps",
    "epsGrowth",
    "epsNext",
    "epsThis",
    "filtered",
    "firm",
    "fiscalQuarter",
    "fiscalYear",
    "growth",
    "high",
    "hold",
    "low",
    "median",
    "month",
    "pt_now",
    "pt_old",
    "rating_new",
    "rating_old",
    "revenue",
    "revenueGrowth",
    "revenueNext",
    "revenueThis",
    "score",
    "scores",
    "sell",
    "slug",
    "strongBuy",
    "strongSell",
    "time",
    "total",
    "updated"
]


STOCK_LIST = {
        "大科技": {"GOOG", "META", "AMZN", "NFLX", "AAPL", "MSFT", "TSLA", "ADBE"},
        "航空郵輪": {"AAL", "LUV", "DAL", "UAL", "ALK", "BA", "CCL", "RCL"},
        "銀行": {"BAC", "JPM", "GS", "C", "WFC", 'NU', 'SOFI'},
        "傳統": {"DIS", "ISRG", "UNH", "ABBV", "CVS", 'TRV'},
        "支付": {"MA", "V", "PYPL", "AXP"},
        "零售": {"LULU", "COST", "PG", "KR", "JWN", "NKE", "DG", "FL", "EL", "PVH", "TPR"},
        "食品": {"HIMS", "CELH","TSN", "MNST", "MCD", "SBUX", "KO", "PEP", "CMG", "YUM", 'DPZ', 'CAKE', 'JACK', 'PLAY', 'FIZZ', 'BLMN', 'DENN', 'DIN'},
        "半導體": {'NVDA', "TSM", "AMD", "QCOM", "MU", "INTC", "ASML", "SWKS", "QRVO", "AVGO", "AMAT", 'MRVL', 'ARM', 'CLS', 'DELL', 'HPE'},
        "原油": {"CVX", "VLO", "COP", "XOM", "OXY",},
        "旅遊": {"BKNG", "EXPE", "MAR", "HLT", "ABNB", "H", "WYNN", "IHG", "LVS", "MGM"},
        "工業": {'NEE', "DE", "HD", "APD", "CAT", "ETN", "HON", "WM", "GE", "MMM", "SUM", "X", 'ENPH', 'SEDG', "FSLR", "VRT", "OKLO"},
        'SaaS': {'SAP', 'CFLT', 'ACN', 'BSX', 'SHOP', 'CRM', 'DDOG', 'NOW', 'INTU', 'SQ', 'WDAY', 'SNOW', 'MDB', 'OKTA', 'ADSK', 'TTD', 'INOD'},
        
        '軟體':   {
            "U", "RBLX",   "SNAP",   "PINS", "Z",   "TTD",    "APP",   "ETSY", "RDDT","DASH",   "TWLO",   "MTCH",   "EXPE",   "UBER", "SPLK",   
            "WDAY",   "OKTA",   "MDB",    "PATH",   "HUBS",
            "CYBR",   "NET",    "ZS",     "PANW",   "CRWD",     "DOCU",
            "PLTR",    "ORCL",    
            "CHKP",   "FTNT",   "AKAM",    "GEN",
        }
    }